### PR TITLE
Improve normalization

### PR DESCRIPTION
**Pull request by zackgalbreath**

### CODE REVIEW

**Comment by jeffbaumes** [comment]
Note that the normalization parameter is supposed to apply column-wise but the scaling I believe is supposed to come afterward and be applied row-wise. I'm think your normalization changes are likely correct but I'm less sure of the scaling changes.

**Comment by jeffbaumes** [comment]
You can check http://www.metaboanalyst.ca/ to see resulting normalizations to check whether what you did matches up.

**Comment by zackgalbreath** [comment]
metaboanalyst agrees with my results for the following operations:
* Cube root transformation
* Mean centering
* Auto scaling
* Pareto scaling
* Range scaling

I'm having trouble getting it to return meaningful results for the Sample Normalization methods (median/sum/etc).  Perhaps my toy dataset is too small?

**Comment by jeffbaumes** [comment]
Great! Given that you've tested all those, and that your median normalization matches what we are seeing in a "real" normalized dataset, I think we are good to go. My only hesitation is whether what I'm calling normalization would normally happen across the rows. But that can be a question for Tom after this is merged.

**Review by jeffbaumes — APPROVED** [review]

**Pull request merged**
